name: merge new link PRs

on: 
    pull_request:
        types:
            - opened

jobs:
    check-pr:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            
            - name: git
              run: |
                git config --global user.name "github-actions"
                git config --global user.email "github-actions@github.com"
            
            - name: sanity check
              run: |
                FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
                if [ $(echo "$FILES" | wc -l) -ne 1 ] || [[ $(echo "$FILES") != *.md ]]; then
                    gh pr close "${{ github.event.pull_request.html_url }}" --delete-branch --comment "try again with a single markdown file"
                    exit 1
                fi
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                

            - name: correct formatting
              run: |
                MD_FILE=$(cat "$FILES")
                
                # Check file format using grep patterns
                if echo "$MD_FILE" | grep -q "^---$" && 
                   echo "$MD_FILE" | grep -q "^layout: forward$" && 
                   echo "$MD_FILE" | grep -q "^target: https://"; then
                    echo "correct file format"
                fi
                else
                    echo "incorrect form rat"
                    gh pr close "${{ github.event.pull_request.html_url }}" --delete-branch --comment "try again bozo"
                    exit 1
                fi
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Approve PR
              run: |
                gh pr review --approve --body "lgtm" "${{ github.event.pull_request.html_url }}" || true
                gh pr merge --auto --delete-branch --subject "yolo" --merge "${{ github.event.pull_request.html_url }}"
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}